-- PostgreSQL DDL for AlphaScan AI User and Task Management

-- Extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users Table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_login_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_users_email ON users(email);

-- Backtest History Table
-- Stores records of each backtest task submitted by a user.
CREATE TABLE backtest_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    task_id VARCHAR(255) UNIQUE NOT NULL, -- A unique ID for the task, can be generated by the Node.js backend
    strategy_name VARCHAR(255) NOT NULL,
    strategy_params JSONB NOT NULL, -- Stores the full configuration of the backtest (symbols, timeframes, indicator conditions)
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING', -- PENDING, RUNNING, COMPLETED, FAILED
    result JSONB, -- Stores the final aggregated statistics from Doris
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT
);

CREATE INDEX idx_backtest_history_user_id ON backtest_history(user_id);
CREATE INDEX idx_backtest_history_task_id ON backtest_history(task_id);
CREATE INDEX idx_backtest_history_status ON backtest_history(status);

-- User-defined Strategy Templates
-- Allows users to save their indicator configurations as templates for later use.
CREATE TABLE strategy_templates (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    template_name VARCHAR(255) NOT NULL,
    description TEXT,
    strategy_params JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, template_name)
);

CREATE INDEX idx_strategy_templates_user_id ON strategy_templates(user_id);

-- Function to automatically update 'updated_at' timestamp
CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers to update 'updated_at' on table updates
CREATE TRIGGER set_timestamp_users
BEFORE UPDATE ON users
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();

CREATE TRIGGER set_timestamp_strategy_templates
BEFORE UPDATE ON strategy_templates
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_timestamp();
